### PR TITLE
Schema updates and fixes found during testing

### LINKED ISSUE #11: The script unable to handle secondary secret expiration
Seems like some incompatibility between database clients and xml clients. 
**Added** extra console logs to capture error details:

Migrating OAuth client 'e661c7f8-4ae1-40e8-bb55-1e34e688cfb3' ...
2024-02-23T14:22:14.45+00:00
```
{
  fields: {
    access_token_ttl: null,
    allow_per_request_redirect_uris: null,
    allowed_origins: null,
    application_url: null,
    audiences: [],
    capabilities: { client_credentials: [Object] },
    claim_mapper_id: null,
    client_authentication: {
      primary: [Object],
      secondary: [Object],
      secondary_verifier_expiration: 1708698134.45
    },
    client_id: 'e661c7f8-4ae1-40e8-bb55-1e34e688cfb3',
    description: 'Human readable service description so that anyone can distinguish what it is about',
    id_token: null,
    logo_uri: null,
    name: 'Service client sample for ***',
    policy_uri: null,
    properties: {
      ITSystemCode: 'ASDADS cannot be empty',
      client_origin: 'client_id creating configuration',
      client_partner_id: 'external partner id if applicable. Otherwise no present',
      correlation_id: 'cf876b7f-0778-40c7-a0c8-ebb936793d38',
      owner: 'Person who owns this client - cannot be empty',
      owner_email: 'email of owner - cannot be empty',
      owner_system_id: '***',
      user_id: '***'
    },
    redirect_uri_validation_policy_id: null,
    redirect_uris: null,
    refresh_token: null,
    request_object: null,
    require_secured_authorization_response: false,
    scopes: [ 'profile' ],
    sector_identifier: null,
    status: 'ACTIVE',
    subject_type: 'public',
    tags: [ 'migrated-from-config' ],
    user_authentication: null,
    userinfo_signed_issuer_id: null,
    tos_uri: null,
    validate_port_on_loopback_interfaces: null
  }
}
```
file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/graphqlClient.ts:135
            throw new Error(errorText);
                  ^

Error: , Variable 'input' has an invalid value: Expected type 'Long' but was 'Double'.
    at GraphqlClient.saveClient (file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/graphqlClient.ts:135:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/index.ts:39:17
   
**** xml (source) exported from Curity Admin UI. 
```
    <config xmlns="http://tail-f.com/ns/config/1.0">
    <profiles xmlns="https://curity.se/ns/conf/base">
    <profile>
    <id>token-service</id>
    <type xmlns:as="https://curity.se/ns/conf/profile/oauth">as:oauth-service</type>
      <settings>
      <authorization-server xmlns="https://curity.se/ns/conf/profile/oauth">
      <client-store>
      <config-backed>
      <client>
        <id>e661c7f8-4ae1-40e8-bb55-1e34e688cfb3</id>
        <client-name>Service client sample for ***</client-name>
        <description>Human readable service description so that anyone can distinguish what it is about</description>
        <secret>***</secret>
        <secondary-authentication-method>
          <expires-on>2024-02-23T14:22:14.45+00:00</expires-on>
          <secret>***</secret>
        </secondary-authentication-method>
        <scope>profile</scope>
        <capabilities>
          <client-credentials/>
        </capabilities>
        <properties>
          <property>
            <key>ITSystemCode</key>
            <value>ASDADS cannot be empty</value>
          </property>
          <property>
            <key>client_origin</key>
            <value>client_id creating configuration</value>
          </property>
          <property>
            <key>client_partner_id</key>
            <value>external partner id if applicable. Otherwise no present</value>
          </property>
          <property>
            <key>correlation_id</key>
            <value>cf876b7f-0778-40c7-a0c8-ebb936793d38</value>
          </property>
          <property>
            <key>owner</key>
            <value>Person who owns this client - cannot be empty</value>
          </property>
          <property>
            <key>owner_email</key>
            <value>email of owner - cannot be empty</value>
          </property>
          <property>
            <key>owner_system_id</key>
            <value>***</value>
          </property>
          <property>
            <key>user_id</key>
            <value>***</value>
          </property>
        </properties>
      </client>
      </config-backed>
      </client-store>
      </authorization-server>
      </settings>
  </profile>
  </profiles>
</config>
```

### LINKED ISSUE #12: Implicit client import does not work.
**From addded console**
```
Migrating OAuth client 'pwd_implicit_test' ...
{
  "id": "pwd_implicit_test",
  "client-name": "pwd_implicit_test",
  "redirect-uris": [
    "https://oauth.tools/callback/implicit"
  ],
  "scope": [
    "openid"
  ],
  "user-authentication": {
    "allowed-authenticators": [
      "username-password"
    ]
  },
  "capabilities": {
    "implicit": [
      null
    ]
  },
  "use-pairwise-subject-identifiers": {
    "sector-identifier": "pwd_implicit_test"
  },
  "validate-port-on-loopback-interfaces": true
}
file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/data/clientMapper.ts:240
            throw new Error(`The client authentication method is not currently supported for ${configClient.id}`);
                  ^

Error: The client authentication method is not currently supported for pwd_implicit_test
    at ClientMapper.getPrimaryClientAuthentication (file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/data/clientMapper.ts:240:19)
    at ClientMapper.getClientAuthentication (file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/data/clientMapper.ts:206:27)
    at ClientMapper.convertToDatabaseClient (file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/data/clientMapper.ts:42:45)
    at file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/index.ts:37:43
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**From xml source.**
```
<config xmlns="http://tail-f.com/ns/config/1.0">
    <profiles xmlns="https://curity.se/ns/conf/base">
    <profile>
    <id>token-service</id>
    <type xmlns:as="https://curity.se/ns/conf/profile/oauth">as:oauth-service</type>
      <settings>
      <authorization-server xmlns="https://curity.se/ns/conf/profile/oauth">
      <client-store>
      <config-backed>
      <client>
        <id>pwd_implicit_test</id>
        <client-name>pwd_implicit_test</client-name>
        <redirect-uris>https://oauth.tools/callback/implicit</redirect-uris>
        <scope>openid</scope>
        <user-authentication>
          <allowed-authenticators>username-password</allowed-authenticators>
        </user-authentication>
        <capabilities>
          <implicit/>
        </capabilities>
        <use-pairwise-subject-identifiers>
          <sector-identifier>pwd_implicit_test</sector-identifier>
        </use-pairwise-subject-identifiers>
        <validate-port-on-loopback-interfaces>true</validate-port-on-loopback-interfaces>
      </client>
      </config-backed>
      </client-store>
      </authorization-server>
      </settings>
  </profile>
  </profiles>
</config>
```

### LINKED ISSUE #13: Uniqueness check fails
Script has issues with uniqueness check, probably due to some default values for getDatabaseClients
```
file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/graphqlClient.ts:135
            throw new Error(errorText);
                  ^

Error: , Exception while fetching data (/createDatabaseClient) : Unable to create client with id: '26a5df8b-ae44-4ba8-ac3a-c0de0b7b70aatesting' in profile 'token-service' as uniqueness check failed    at GraphqlClient.saveClient (file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/graphqlClient.ts:135:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/index.ts:39:17
```

The graphql query from script
```
        const query = gql`
            query getDatabaseClients {
                databaseClients {
                    edges {
                        node {
                            client_id
                        }
                    }
                }
            }`;
```

Dirt fix to this fixed the issue
```
        const query = gql`
            query getDatabaseClients {
                databaseClients(first: 200) {
                    edges {
                        node {
                            client_id
                        }
                    }
                }
            }`;
```
This behavior regarding default value for first does not seem to be documented through graphql introspection. 

image

image

image

### PR DESCRIPTION
**Pull request by gary-archer**
**SCHEMA**

Update to 9.3 schema and use standards-credential-mode

**VERSION PROBLEMS FIXED**

- There was an import problem in `migration-configuration.xml`, where previously `dbClient.*` was allowed but it now needs to be `dbClient`. 
- There was a problem where tags now need to be included in the XML configuration before you can set them when saving a DB client.

Note also that since this repo was written the DB clients are not also available in the admin UI.

**ISSUES REPORTED**

- Fixed [this reported issue](https://github.com/curityio/database-client-migration-example/issues/11) where a fractional secondary expiration time was not handled correctly
- Fixed [this reported issue](https://github.com/curityio/database-client-migration-example/issues/12) where an implicit flow client did not get migrated correctly.
- Fixed [this reported issue](https://github.com/curityio/database-client-migration-example/issues/13) by setting a large `first` size to override the GraphQL DEFAULT_PAGE_SIZE value of 20

**TYPE CHANGES**

I updated dependencies and regenerated the `databaseClient.ts` file, which has a couple of changes. These are just a TypeScript naming thing and the actual objects are unchanged, but good to avoid warnings for developers looking at this:

- ClientAuthenticationInput -> ClientAuthenticationCreateInput
- ClientAuthenticationVerifierInput -> ClientAuthenticationVerifierCreateInput
- IdTokenInput -> IdTokenCreateInput

### CODE REVIEW

File: src/data/databaseClient.ts [hunk 1]
```diff
@@ -1,19 +1,3 @@
-/*
```
Comment (mtrojanowski) [inline src/data/databaseClient.ts:1]: Should we retain this copyright notice?

File: src/graphqlClient.ts [hunk 2]
```diff
@@ -77,7 +78,7 @@ export class GraphqlClient {
 
         const query = gql`
             query getDatabaseClients {
-                databaseClients {
```
Comment (mtrojanowski) [inline src/graphqlClient.ts:80]: I know this is demo-level, but maybe there should be a note in readme that this script works only if you have fewer than 1000 clients.

**Review by mtrojanowski — APPROVED** [review]
